/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.AircraftCollection');

goog.require('jspb.Message');
goog.require('proto.AircraftMeta');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AircraftCollection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AircraftCollection.repeatedFields_, null);
};
goog.inherits(proto.AircraftCollection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.AircraftCollection.displayName = 'proto.AircraftCollection';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AircraftCollection.repeatedFields_ = [15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AircraftCollection.prototype.toObject = function(opt_includeInstance) {
  return proto.AircraftCollection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AircraftCollection} msg The msg instance to transform.
 * @return {!Object}
 */
proto.AircraftCollection.toObject = function(includeInstance, msg) {
  var f, obj = {
    now: msg.getNow(),
    messages: msg.getMessages(),
    aircraftList: jspb.Message.toObjectList(msg.getAircraftList(),
    proto.AircraftMeta.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.AircraftCollection} The clone.
 */
proto.AircraftCollection.prototype.cloneMessage = function() {
  return /** @type {!proto.AircraftCollection} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint64 now = 1;
 * @return {number}
 */
proto.AircraftCollection.prototype.getNow = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.AircraftCollection.prototype.setNow = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint64 messages = 2;
 * @return {number}
 */
proto.AircraftCollection.prototype.getMessages = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.AircraftCollection.prototype.setMessages = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated AircraftMeta aircraft = 15;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.AircraftMeta>}
 */
proto.AircraftCollection.prototype.getAircraftList = function() {
  return /** @type{!Array.<!proto.AircraftMeta>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AircraftMeta, 15));
};


/** @param {Array.<!proto.AircraftMeta>} value  */
proto.AircraftCollection.prototype.setAircraftList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 15, value);
};


proto.AircraftCollection.prototype.clearAircraftList = function() {
  this.setAircraftList([]);
};


