/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.IdxAircraft');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.IdxAircraft = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.IdxAircraft, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.IdxAircraft.displayName = 'proto.IdxAircraft';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.IdxAircraft.prototype.toObject = function(opt_includeInstance) {
  return proto.IdxAircraft.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.IdxAircraft} msg The msg instance to transform.
 * @return {!Object}
 */
proto.IdxAircraft.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: msg.getAddress(),
    registration: msg.getRegistration(),
    type: msg.getType(),
    description: msg.getDescription(),
    military: msg.getMilitary(),
    interesting: msg.getInteresting()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.IdxAircraft} The clone.
 */
proto.IdxAircraft.prototype.cloneMessage = function() {
  return /** @type {!proto.IdxAircraft} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint32 address = 1;
 * @return {number}
 */
proto.IdxAircraft.prototype.getAddress = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.IdxAircraft.prototype.setAddress = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string registration = 2;
 * @return {string}
 */
proto.IdxAircraft.prototype.getRegistration = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.IdxAircraft.prototype.setRegistration = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string type = 3;
 * @return {string}
 */
proto.IdxAircraft.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.IdxAircraft.prototype.setType = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.IdxAircraft.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.IdxAircraft.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional bool military = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.IdxAircraft.prototype.getMilitary = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 5, false));
};


/** @param {boolean} value  */
proto.IdxAircraft.prototype.setMilitary = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional bool interesting = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.IdxAircraft.prototype.getInteresting = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 6, false));
};


/** @param {boolean} value  */
proto.IdxAircraft.prototype.setInteresting = function(value) {
  jspb.Message.setField(this, 6, value);
};


