/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.IdxDatabase');

goog.require('jspb.Message');
goog.require('proto.IdxAircraft');
goog.require('proto.IdxOperator');
goog.require('proto.IdxType');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.IdxDatabase = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.IdxDatabase.repeatedFields_, null);
};
goog.inherits(proto.IdxDatabase, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.IdxDatabase.displayName = 'proto.IdxDatabase';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.IdxDatabase.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.IdxDatabase.prototype.toObject = function(opt_includeInstance) {
  return proto.IdxDatabase.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.IdxDatabase} msg The msg instance to transform.
 * @return {!Object}
 */
proto.IdxDatabase.toObject = function(includeInstance, msg) {
  var f, obj = {
    dbVersion: msg.getDbVersion(),
    dbTypesList: jspb.Message.toObjectList(msg.getDbTypesList(),
    proto.IdxType.toObject, includeInstance),
    dbOperatorsList: jspb.Message.toObjectList(msg.getDbOperatorsList(),
    proto.IdxOperator.toObject, includeInstance),
    dbAircraftsList: jspb.Message.toObjectList(msg.getDbAircraftsList(),
    proto.IdxAircraft.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.IdxDatabase} The clone.
 */
proto.IdxDatabase.prototype.cloneMessage = function() {
  return /** @type {!proto.IdxDatabase} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint32 db_version = 1;
 * @return {number}
 */
proto.IdxDatabase.prototype.getDbVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.IdxDatabase.prototype.setDbVersion = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated IdxType db_types = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.IdxType>}
 */
proto.IdxDatabase.prototype.getDbTypesList = function() {
  return /** @type{!Array.<!proto.IdxType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.IdxType, 2));
};


/** @param {Array.<!proto.IdxType>} value  */
proto.IdxDatabase.prototype.setDbTypesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


proto.IdxDatabase.prototype.clearDbTypesList = function() {
  this.setDbTypesList([]);
};


/**
 * repeated IdxOperator db_operators = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.IdxOperator>}
 */
proto.IdxDatabase.prototype.getDbOperatorsList = function() {
  return /** @type{!Array.<!proto.IdxOperator>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.IdxOperator, 3));
};


/** @param {Array.<!proto.IdxOperator>} value  */
proto.IdxDatabase.prototype.setDbOperatorsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.IdxDatabase.prototype.clearDbOperatorsList = function() {
  this.setDbOperatorsList([]);
};


/**
 * repeated IdxAircraft db_aircrafts = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.IdxAircraft>}
 */
proto.IdxDatabase.prototype.getDbAircraftsList = function() {
  return /** @type{!Array.<!proto.IdxAircraft>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.IdxAircraft, 4));
};


/** @param {Array.<!proto.IdxAircraft>} value  */
proto.IdxDatabase.prototype.setDbAircraftsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.IdxDatabase.prototype.clearDbAircraftsList = function() {
  this.setDbAircraftsList([]);
};


