/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.IdxOperator');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.IdxOperator = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.IdxOperator, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.IdxOperator.displayName = 'proto.IdxOperator';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.IdxOperator.prototype.toObject = function(opt_includeInstance) {
  return proto.IdxOperator.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.IdxOperator} msg The msg instance to transform.
 * @return {!Object}
 */
proto.IdxOperator.toObject = function(includeInstance, msg) {
  var f, obj = {
    ident: msg.getIdent(),
    name: msg.getName(),
    country: msg.getCountry(),
    callsign: msg.getCallsign()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.IdxOperator} The clone.
 */
proto.IdxOperator.prototype.cloneMessage = function() {
  return /** @type {!proto.IdxOperator} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string ident = 1;
 * @return {string}
 */
proto.IdxOperator.prototype.getIdent = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.IdxOperator.prototype.setIdent = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.IdxOperator.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.IdxOperator.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string country = 3;
 * @return {string}
 */
proto.IdxOperator.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.IdxOperator.prototype.setCountry = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string callsign = 4;
 * @return {string}
 */
proto.IdxOperator.prototype.getCallsign = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.IdxOperator.prototype.setCallsign = function(value) {
  jspb.Message.setField(this, 4, value);
};


