/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.StatisticEntry');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.StatisticEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.StatisticEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.StatisticEntry.displayName = 'proto.StatisticEntry';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.StatisticEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.StatisticEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.StatisticEntry} msg The msg instance to transform.
 * @return {!Object}
 */
proto.StatisticEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    start: msg.getStart(),
    stop: msg.getStop(),
    messages: msg.getMessages(),
    maxDistanceInMetres: msg.getMaxDistanceInMetres(),
    maxDistanceInNauticalMiles: msg.getMaxDistanceInNauticalMiles(),
    altitudeSuppressed: msg.getAltitudeSuppressed(),
    tracksAll: msg.getTracksAll(),
    tracksSingleMessage: msg.getTracksSingleMessage(),
    cpuDemod: msg.getCpuDemod(),
    cpuReader: msg.getCpuReader(),
    cpuBackground: msg.getCpuBackground(),
    cprSurface: msg.getCprSurface(),
    cprAirborne: msg.getCprAirborne(),
    cprGlobalOk: msg.getCprGlobalOk(),
    cprGlobalBad: msg.getCprGlobalBad(),
    cprGlobalRange: msg.getCprGlobalRange(),
    cprGlobalSpeed: msg.getCprGlobalSpeed(),
    cprGlobalSkipped: msg.getCprGlobalSkipped(),
    cprLocalOk: msg.getCprLocalOk(),
    cprLocalAircraftRelative: msg.getCprLocalAircraftRelative(),
    cprLocalReceiverRelative: msg.getCprLocalReceiverRelative(),
    cprLocalSkipped: msg.getCprLocalSkipped(),
    cprLocalRange: msg.getCprLocalRange(),
    cprLocalSpeed: msg.getCprLocalSpeed(),
    cprFiltered: msg.getCprFiltered(),
    remoteModeac: msg.getRemoteModeac(),
    remoteModes: msg.getRemoteModes(),
    remoteBad: msg.getRemoteBad(),
    remoteUnknownIcao: msg.getRemoteUnknownIcao(),
    localSamplesProcessed: msg.getLocalSamplesProcessed(),
    localSamplesDropped: msg.getLocalSamplesDropped(),
    localModeac: msg.getLocalModeac(),
    localModes: msg.getLocalModes(),
    localBad: msg.getLocalBad(),
    localUnknownIcao: msg.getLocalUnknownIcao(),
    localStrongSignals: msg.getLocalStrongSignals(),
    localSignal: msg.getLocalSignal(),
    localNoise: msg.getLocalNoise(),
    localPeakSignal: msg.getLocalPeakSignal()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.StatisticEntry} The clone.
 */
proto.StatisticEntry.prototype.cloneMessage = function() {
  return /** @type {!proto.StatisticEntry} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint64 start = 1;
 * @return {number}
 */
proto.StatisticEntry.prototype.getStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setStart = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint64 stop = 2;
 * @return {number}
 */
proto.StatisticEntry.prototype.getStop = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setStop = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint64 messages = 3;
 * @return {number}
 */
proto.StatisticEntry.prototype.getMessages = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setMessages = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint32 max_distance_in_metres = 4;
 * @return {number}
 */
proto.StatisticEntry.prototype.getMaxDistanceInMetres = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setMaxDistanceInMetres = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional uint32 max_distance_in_nautical_miles = 5;
 * @return {number}
 */
proto.StatisticEntry.prototype.getMaxDistanceInNauticalMiles = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 5, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setMaxDistanceInNauticalMiles = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional uint64 altitude_suppressed = 6;
 * @return {number}
 */
proto.StatisticEntry.prototype.getAltitudeSuppressed = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 6, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setAltitudeSuppressed = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional uint64 tracks_all = 7;
 * @return {number}
 */
proto.StatisticEntry.prototype.getTracksAll = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 7, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setTracksAll = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional uint64 tracks_single_message = 8;
 * @return {number}
 */
proto.StatisticEntry.prototype.getTracksSingleMessage = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 8, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setTracksSingleMessage = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional uint64 cpu_demod = 20;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCpuDemod = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 20, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCpuDemod = function(value) {
  jspb.Message.setField(this, 20, value);
};


/**
 * optional uint64 cpu_reader = 21;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCpuReader = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 21, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCpuReader = function(value) {
  jspb.Message.setField(this, 21, value);
};


/**
 * optional uint64 cpu_background = 22;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCpuBackground = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 22, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCpuBackground = function(value) {
  jspb.Message.setField(this, 22, value);
};


/**
 * optional uint64 cpr_surface = 40;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprSurface = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 40, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprSurface = function(value) {
  jspb.Message.setField(this, 40, value);
};


/**
 * optional uint64 cpr_airborne = 41;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprAirborne = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 41, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprAirborne = function(value) {
  jspb.Message.setField(this, 41, value);
};


/**
 * optional uint64 cpr_global_ok = 42;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprGlobalOk = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 42, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprGlobalOk = function(value) {
  jspb.Message.setField(this, 42, value);
};


/**
 * optional uint64 cpr_global_bad = 43;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprGlobalBad = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 43, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprGlobalBad = function(value) {
  jspb.Message.setField(this, 43, value);
};


/**
 * optional uint64 cpr_global_range = 44;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprGlobalRange = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 44, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprGlobalRange = function(value) {
  jspb.Message.setField(this, 44, value);
};


/**
 * optional uint64 cpr_global_speed = 45;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprGlobalSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 45, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprGlobalSpeed = function(value) {
  jspb.Message.setField(this, 45, value);
};


/**
 * optional uint64 cpr_global_skipped = 46;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprGlobalSkipped = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 46, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprGlobalSkipped = function(value) {
  jspb.Message.setField(this, 46, value);
};


/**
 * optional uint64 cpr_local_ok = 47;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprLocalOk = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 47, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprLocalOk = function(value) {
  jspb.Message.setField(this, 47, value);
};


/**
 * optional uint64 cpr_local_aircraft_relative = 48;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprLocalAircraftRelative = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 48, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprLocalAircraftRelative = function(value) {
  jspb.Message.setField(this, 48, value);
};


/**
 * optional uint64 cpr_local_receiver_relative = 49;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprLocalReceiverRelative = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 49, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprLocalReceiverRelative = function(value) {
  jspb.Message.setField(this, 49, value);
};


/**
 * optional uint64 cpr_local_skipped = 50;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprLocalSkipped = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 50, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprLocalSkipped = function(value) {
  jspb.Message.setField(this, 50, value);
};


/**
 * optional uint64 cpr_local_range = 51;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprLocalRange = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 51, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprLocalRange = function(value) {
  jspb.Message.setField(this, 51, value);
};


/**
 * optional uint64 cpr_local_speed = 52;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprLocalSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 52, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprLocalSpeed = function(value) {
  jspb.Message.setField(this, 52, value);
};


/**
 * optional uint64 cpr_filtered = 53;
 * @return {number}
 */
proto.StatisticEntry.prototype.getCprFiltered = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 53, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setCprFiltered = function(value) {
  jspb.Message.setField(this, 53, value);
};


/**
 * optional uint64 remote_modeac = 70;
 * @return {number}
 */
proto.StatisticEntry.prototype.getRemoteModeac = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 70, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setRemoteModeac = function(value) {
  jspb.Message.setField(this, 70, value);
};


/**
 * optional uint64 remote_modes = 71;
 * @return {number}
 */
proto.StatisticEntry.prototype.getRemoteModes = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 71, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setRemoteModes = function(value) {
  jspb.Message.setField(this, 71, value);
};


/**
 * optional uint64 remote_bad = 72;
 * @return {number}
 */
proto.StatisticEntry.prototype.getRemoteBad = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 72, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setRemoteBad = function(value) {
  jspb.Message.setField(this, 72, value);
};


/**
 * optional uint64 remote_unknown_icao = 73;
 * @return {number}
 */
proto.StatisticEntry.prototype.getRemoteUnknownIcao = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 73, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setRemoteUnknownIcao = function(value) {
  jspb.Message.setField(this, 73, value);
};


/**
 * optional uint64 local_samples_processed = 90;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalSamplesProcessed = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 90, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalSamplesProcessed = function(value) {
  jspb.Message.setField(this, 90, value);
};


/**
 * optional uint64 local_samples_dropped = 91;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalSamplesDropped = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 91, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalSamplesDropped = function(value) {
  jspb.Message.setField(this, 91, value);
};


/**
 * optional uint64 local_modeac = 92;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalModeac = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 92, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalModeac = function(value) {
  jspb.Message.setField(this, 92, value);
};


/**
 * optional uint64 local_modes = 93;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalModes = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 93, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalModes = function(value) {
  jspb.Message.setField(this, 93, value);
};


/**
 * optional uint64 local_bad = 94;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalBad = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 94, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalBad = function(value) {
  jspb.Message.setField(this, 94, value);
};


/**
 * optional uint64 local_unknown_icao = 95;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalUnknownIcao = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 95, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalUnknownIcao = function(value) {
  jspb.Message.setField(this, 95, value);
};


/**
 * optional uint64 local_strong_signals = 96;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalStrongSignals = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 96, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalStrongSignals = function(value) {
  jspb.Message.setField(this, 96, value);
};


/**
 * optional float local_signal = 97;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalSignal = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 97, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalSignal = function(value) {
  jspb.Message.setField(this, 97, value);
};


/**
 * optional float local_noise = 98;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalNoise = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 98, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalNoise = function(value) {
  jspb.Message.setField(this, 98, value);
};


/**
 * optional float local_peak_signal = 99;
 * @return {number}
 */
proto.StatisticEntry.prototype.getLocalPeakSignal = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 99, 0));
};


/** @param {number} value  */
proto.StatisticEntry.prototype.setLocalPeakSignal = function(value) {
  jspb.Message.setField(this, 99, value);
};


